config/routes.rb
Rails.application.routes.draw do
  
  get 'errors/not_found'

  get 'errors/internal_server_error'

  # Routes for main resources
  resources :items
  resources :purchases
  resources :item_prices
  resources :users
  resources :schools
  resources :orders
  resources :sessions

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  # shipper ajax
  get "home/toggle/:id" => "home#toggle", as: :toggle

  # cart stuff
  get "view_cart" => "home#view_cart", as: :view_cart
  post "items/add_to_cart/:id" => "items#add_to_cart", as: :add_to_cart
  post "items/remove_one_from_cart/:id" => "items#remove_one_from_cart", as: :remove_one_from_cart
  post "items/delete_from_cart/:id" => "items#delete_from_cart", as: :delete_from_cart

  # error routes
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # Set the root url
  root :to => 'home#home'  

end

app/views/partials/_cart_tables.html.erb
<table class = "bordered centered responsive-table">
  <thead>
    <th>Item</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Subtotal</th>
    <th></th>
  </thead>
  <tbody>
    <% for i in @cart_items %>
      <tr>
        <td><%= link_to i.item.name, item_path(i.item) %></td>
        <td><%= number_to_currency(i.item.current_price) %>
        <td>
          <%= button_to "+", add_to_cart_path(i.item.id) %>
          <%= i.quantity %>
          <%= button_to "-", remove_one_from_cart_path(i.item.id)%>
        </td>
        <td><%= number_to_currency(i.item.current_price * i.quantity) %></td>
        <td><%= button_to "Delete", delete_from_cart_path(i.item.id)%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<table class="col s3">
  <tbody>
    <tr>
      <td><b>Subtotal: </b></td><td><%= number_to_currency(cart_cost) %></td>
    </tr>
    <tr>
      <td><b>Shipping Cost: </b></td><td><%= number_to_currency(shipping_cost) %></td>
    </tr>
    <tr>
      <td><b>Grand Total: </b></td><td><%= number_to_currency(cart_cost + shipping_cost) %></td>
    </tr>
  </tbody>
</table>

app/views/partials/_dropdown_content.html.erb
<ul id="account_dropdown" class="dropdown-content">
  <li><%= link_to "View Profile", user_path(current_user.id) %></li>
  <li><%= link_to "Edit Account", edit_user_path(current_user.id) %></li>
  <li><%= link_to "Logout", logout_path %></li>
</ul>

<ul id="menu_dropdown" class="dropdown-content">
  <li><%= link_to "Home", home_path %></li>
  <li><%= link_to "Items", items_path %></li>
  <li><%= link_to "Prices", item_prices_path %></li>
  <li><%= link_to "Purchases", purchases_path %></li>
  <li><%= link_to "Schools", schools_path %></li>
  <li><%= link_to "Users", users_path %></li>
  <li><%= link_to "Orders", orders_path %></li>
</ul>

<ul id="quick_options_dropdown" class="dropdown-content">
  <li><%= link_to "Add an Item", new_item_path %></li>
  <li><%= link_to "Change an Item's Price", new_item_price_path %></li>
  <li><%= link_to "Make a Purchase", new_purchase_path %></li>
  <% if current_user.role?(:admin) %>
    <li><%= link_to "Add a School", new_school_path %></li>
    <li><%= link_to "Add a User", new_user_path %></li>
  <% elsif current_user.role?(:manager) %>
    <li><%= link_to "Add an Employee", new_user_path %></li>
  <% end %>

  
</ul>

app/views/partials/_footer.html.erb
<footer class="page-footer teal">
	<div class="container">
		<div class="row">
			<div class="col l6 s12">
				<h5 class="white-text">Questions, Comments, or Concerns?</h5>
				<p class="grey-text text-lighten-4">Please get in touch with the Webmaster. The email is linked below and the contact information is listed in the Contact page.</p>
				<p class="grey-text text-lighten-4"> &copy 2017 Webmaster: <a class="grey-text text-lighten-4" <%= mail_to("wpchu@andrew.cmu.edu", "Winston Chu", encode: "javascript") %> </a> </p>
			</div>
			<div class="col l4 offset-l2 s12">
				<h5 class="white-text">Links</h5>
				<ul>
					<div id="footer">
						<li><a class="grey-text text-lighten-3" <%= link_to 'Home', home_path %> </a></li>
						<li><a class="grey-text text-lighten-3" <%= link_to 'About', about_path %> </a></li>
						<li><a class="grey-text text-lighten-3" <%= link_to 'Contact Us', contact_path %> </a></li>
						<li><a class="grey-text text-lighten-3" <%= link_to 'Privacy Policy', privacy_path %> </a></li>
					</div>
				</ul>
			</div>
		</div>
	</div>
</footer>

app/views/partials/_login_modal.html.erb
<div id="loginModal" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h5 class="black-text">Please use your email and password to login to our system.</h5>
    <%= form_tag sessions_path do %>
      <div class="control-group">
        <%= label_tag :email %>
        <div class="controls black-text">
          <%= text_field_tag :email, params[:email] %>
        </div>
      </div>
      <div class="control-group">
        <%= label_tag :password %>
        <div class="controls black-text">
          <%= password_field_tag :password %>
        </div>
      </div>
      <div class="actions">
      	<button class="btn waves-effect waves-light">
          <%= submit_tag "Login"%>
				</button>
      </div>
    <% end %>
  </div>
</div>

app/views/partials/_nav.html.erb
<div class="nav-wrapper teal">
  <div class="top-bar">
    <a class="brand-logo" <%= link_to "Alex & Mark's Chess Store", home_path %> </a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if logged_in? %>
        <% if current_user.role?(:customer) || current_user.role?(:shipper) %>
          <li><%= link_to "Browse Items", items_path %></li>
          <% if current_user.role?(:customer) %>
            <li><%= link_to "Add School", new_school_path %></li>
            <li><%= link_to "View Cart (#{session[:cart].length})", view_cart_path %></li>
          <% end %>
        <% elsif current_user.role?(:admin) || current_user.role?(:manager) %>
          <% if current_user.role?(:admin) %>
            <li><%= link_to "View Cart (#{session[:cart].length})", view_cart_path %></li>
          <% end %>
          <li><a class="dropdown-button" data-activates="menu_dropdown">Menu<i class="material-icons right">arrow_drop_down</i></a></li>
          <li><a class="dropdown-button" data-activates="quick_options_dropdown">Quick Options<i class="material-icons right">arrow_drop_down</i></a></li>
        <% end %>
        <!-- Dropdown Content -->
        <%= render partial: 'partials/dropdown_content' %>
        <li><a class="dropdown-button" data-activates="account_dropdown">Welcome, <%= current_user.first_name %><i class="material-icons right">arrow_drop_down</i></a></li>
      <% elsif !logged_in? %>
        <li><%= link_to "Browse Items", items_path %></li>
        <li> <%= link_to "Create Account", new_user_path %>
        <li> <%= link_to "Login", login_path %> </li>
      <% end%>  
    </ul>
  </div>
</div>

app/views/partials/_side_bar.html.erb
<div id="side_bar">
  <u><h5>Menu:</h5></u>
    <li><%= link_to "Home", home_path %></li>
    <li><%= link_to "View Items", items_path %></li>
    <li><%= link_to "View Item Prices", item_prices_path %></li>
    <li><%= link_to "View Purchases", purchases_path %></li>
    <li><%= link_to "View Schools", schools_path %></li>
    <li><%= link_to "View Users", users_path %></li>
    <li><%= link_to "View Orders", orders_path %></li>

  <u><h5>Quick Options:</h5></u>
    <li><%= link_to "Add an Item", new_item_path %></li>
    <li><%= link_to "Change an Item's Price", new_item_price_path %></li>
    <li><%= link_to "Make a Purchase", new_purchase_path %></li>
    <% if current_user.role?(:admin) %>
      <li><%= link_to "Add a School", new_school_path %></li>
    <% end %>
    <li><%= link_to "Add a User", new_user_path %></li>
</div>