config/routes.rb
Rails.application.routes.draw do
  
  get 'errors/not_found'

  get 'errors/internal_server_error'

  # Routes for main resources
  resources :items
  resources :purchases
  resources :item_prices
  resources :users
  resources :schools
  resources :orders
  resources :sessions

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  # shipper ajax
  get "home/toggle/:id" => "home#toggle", as: :toggle

  # cart stuff
  get "view_cart" => "home#view_cart", as: :view_cart
  post "items/add_to_cart/:id" => "items#add_to_cart", as: :add_to_cart
  post "items/remove_one_from_cart/:id" => "items#remove_one_from_cart", as: :remove_one_from_cart
  post "items/delete_from_cart/:id" => "items#delete_from_cart", as: :delete_from_cart

  # error routes
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # Set the root url
  root :to => 'home#home'  

end

app/models/user.rb
class User < ActiveRecord::Base
  # get modules to help with some functionality
  include ChessStoreHelpers::Validations

  # use has_secure_password
  has_secure_password

  # Relationships
  has_many :orders

  # Scopes
  scope :alphabetical,  -> { order(:last_name).order(:first_name) }
  scope :active,        -> { where(active: true) }
  scope :inactive,      -> { where(active: false) }
  scope :employees,     -> { where.not(role: 'customer') }
  scope :customers,     -> { where(role: 'customer') }

  # Validations
  validates :username, presence: true, uniqueness: { case_sensitive: false}
  validates :email, presence: true, uniqueness: { case_sensitive: false}, format: { with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, message: "is not a valid format" }
  validates :phone, format: { with: /\A\(?\d{3}\)?[-. ]?\d{3}[-.]?\d{4}\z/, message: "should be 10 digits (area code needed) and delimited with dashes only", allow_blank: true }
  validates :role, inclusion: { in: %w[admin manager shipper customer], message: "is not a recognized role in system" }
  validates_presence_of :password, on: :create 
  validates_presence_of :password_confirmation, on: :create 
  validates_confirmation_of :password, on: :create, message: "does not match"
  validates_length_of :password, minimum: 4, message: "must be at least 4 characters long", allow_blank: true

  # For use in authorizing with CanCan
  ROLES = [['Administrator', :admin],['Manager', :manager],['Shipper', :shipper],['Customer',:customer]]

  def role?(authorized_role)
    return false if role.nil?
    role.downcase.to_sym == authorized_role
  end
  
  # Other methods
  def name
    "#{last_name}, #{first_name}"
  end

  def proper_name
    "#{first_name} #{last_name}"
  end

  # Callbacks
  before_destroy :is_never_destroyable
  before_save :reformat_phone
  
  private
  def reformat_phone
    phone = self.phone.to_s  # change to string in case input as all numbers 
    phone.gsub!(/[^0-9]/,"") # strip all non-digits
    self.phone = phone       # reset self.phone to new string
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include ChessStoreHelpers::Cart

  before_action :set_user, only: [:show, :edit, :update]
  load_and_authorize_resource

  def index
    @active_users = User.active.alphabetical.paginate(page: params[:page]).per_page(10)
    @inactive_users = User.inactive.alphabetical.paginate(page: params[:page]).per_page(10)
    @employees = User.employees.alphabetical.paginate(page: params[:page]).per_page(10)
    @customers = User.customers.alphabetical.paginate(page: params[:page]).per_page(10)
  end

  def new
    @user = User.new
    unless logged_in? && (current_user.role?(:manager) || current_user.role?(:admin))
      session[:user_id] = @user.id
    end
  end

  def edit
  end

  def show
    @user_orders = @user.orders.all.chronological.paginate(page: params[:page]).per_page(10)
    @reformatted_phone = "(#{@user.phone[0..2]}) #{@user.phone[3..5]}-#{@user.phone[6..9]}"
  end

  def create
    @user = User.new(user_params)
    if @user.save
      if !logged_in?
        session[:user_id] = @user.id
        create_cart
        redirect_to home_path, notice: "Welcome, #{@user.first_name}. Thank you for signing up!"
      else
        redirect_to user_path(@user), notice: "Successfully created #{@user.proper_name}."
      end
    else
      flash[:error] = "This user could not be created."
      render "new"
    end
  end

  def update
    if @user.update_attributes(user_params)
      flash[:notice] = "#{@user.proper_name} was successfully updated."
      redirect_to @user
    else
      render :action => 'edit'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    if current_user && (current_user.role?(:admin) || current_user.role?(:manager))
      params.require(:user).permit(:first_name, :last_name, :email, :phone, :username, :password, :password_confirmation, :role, :active) 
    else
      params.require(:user).permit(:first_name, :last_name, :email, :phone, :username, :password, :password_confirmation, :role) 
    end
  end

end

app/views/users/_active_users.html.erb
<!-- Display a table showing information of all the boards -->
<table class="bordered highlight responsive-table">
	<thead>
		<tr>
			<th>Name (Username)</th>
      <th>Email</th>
			<th>Role</th>
			<% if current_user.role?(:admin) %>
				<th></th>
			<% end %>
		</tr>
	</thead>

	<tbody>
		<% for user in @active_users %>
      <tr>
        <td><%= link_to user.name, user_path(user) %><%= " (#{user.username})" %></td>
        <td><%= mail_to(user.email, user.email, encode: "javascript") %></td>
        <td><%= user.role.capitalize %></td>
				<% if current_user.role?(:admin) %>
					<td><a class="waves-effect waves-teal btn" <%= link_to "Edit", edit_user_path(user) %> </a></td>
				<% end %>
      </tr>
		<% end %>
	</tbody>
</table>

<%= will_paginate @active_users %>

app/views/users/_customers.html.erb
<!-- Display a table showing information of all the boards -->
<table class="bordered highlight responsive-table">
	<thead>
		<tr>
			<th>Name (Username)</th>
      <th>Email</th>
			<th>Active</th>
			<% if current_user.role?(:admin) %>
				<th></th>
			<% end %>
		</tr>
	</thead>

	<tbody>
		<% for user in @customers %>
      <tr>
        <td><%= link_to user.name, user_path(user) %><%= " (#{user.username})" %></td>
        <td><%= mail_to(user.email, user.email, encode: "javascript") %></td>
        <td>
          <% if user.active? %>
            Y
          <% else %>
            N
          <% end %>
        </td>
				<% if current_user.role?(:admin) %>
					<td><a class="waves-effect waves-teal btn" <%= link_to "Edit", edit_user_path(user) %> </a></td>
				<% end %>
      </tr>
		<% end %>
	</tbody>
</table>

<%= will_paginate @customers %>

app/views/users/_employees.html.erb
<!-- Display a table showing information of all the boards -->
<table class="bordered highlight responsive-table">
	<thead>
		<tr>
			<th>Name (Username)</th>
      <th>Email</th>
      <th>Role</th>
			<th>Active</th>
			<% if current_user.role?(:admin) || current_user.role?(:manager) %>
				<th></th>
			<% end %>
		</tr>
	</thead>

	<tbody>
		<% for user in @employees %>
      <tr>
        <td><%= link_to user.name, user_path(user) %><%= " (#{user.username})" %></td>
        <td><%= mail_to(user.email, user.email, encode: "javascript") %></td>
        <td><%= user.role.capitalize %></td>
        <td>
          <% if user.active? %>
            Y
          <% else %>
            N
          <% end %>
        </td>
				<% if current_user.role?(:admin) || current_user.role?(:manager) %>
					<td><a class="waves-effect waves-teal btn" <%= link_to "Edit", edit_user_path(user) %> </a></td>
				<% end %>
      </tr>
		<% end %>
	</tbody>
</table>

<%= will_paginate @employees %>

app/views/users/_form.html.erb
<div class="row">
	<%= simple_form_for(@user) do |f| %>

		<!-- Display errors, if any -->
		<% if @user.errors.any? %>
			<div id="error_explanation">
				<h6><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h6>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</div>
  	<% end %>
		
		<!-- guests MUST register as a customer -->
		<% unless logged_in? %>
			<%= f.input :role, as: :hidden, input_html: { value: "customer" } %>
		<% end %>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">person</i>
				<%= f.label :first_name %>
    		<%= f.text_field :first_name %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">person</i>
				<%= f.label :last_name %>
    		<%= f.text_field :last_name %>
			</div>
    </div>
    <% unless @user.save %>
      <div class="row">
        <div class="input-field col s10">
          <i class="material-icons prefix">person_outline</i>
          <%= f.label :username %>
          <%= f.text_field :username %>
        </div>
      </div>
    <% end %>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">email</i>
				<%= f.label :email %>
    		<%= f.text_field :email %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">phone</i>
				<%= f.label :phone %>
    		<%= f.text_field :phone %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">lock_outline</i>
				<%= f.label :password %>
				<input type="password"<%= f.text_field :password %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">lock</i>
				<%= f.label :password_confirmation %>
				<input type="password"<%= f.text_field :password_confirmation %>
			</div>
		</div>
		<% unless @user.save %>
			<% unless !logged_in? %>
				<div class="row">
					<div class="input-field col s10">
						<i class="material-icons prefix">list</i>
						<%= f.label :role %><br></br>
						<% if logged_in? && current_user.role?(:admin) %>
							<%= f.select :role, User::ROLES %>
						<% elsif logged_in? && current_user.role?(:manager)%>
							<%= f.select :role, User::ROLES, :disabled => [:customer] %>
						<% end %>
					</div>
				</div>
			<% end %>
		<% end %>
		<% if logged_in? && (current_user.role?(:manager) || current_user.role?(:admin)) %>
			<div class="row">
				<div class="input-field col s10">
					<%= f.input :active, as: :boolean %>
				</div>
			</div>
		<% end %>
		<div class ="row">
			<div class="input-field col s10">
				<button class="btn waves-effect waves-light">
					<i class="material-icons right">verified_user</i>
					<%= f.submit %>
				</button>
			</div>
		</div>
	<% end %>
</div>

app/views/users/_inactive_users.html.erb
<!-- Display a table showing information of all the boards -->
<table class="bordered highlight responsive-table">
	<thead>
		<tr>
			<th>Name (Username)</th>
      <th>Email</th>
			<th>Role</th>
			<% if current_user.role?(:admin) %>
				<th></th>
			<% end %>
		</tr>
	</thead>

	<tbody>
		<% for user in @inactive_users %>
      <tr>
        <td><%= link_to user.name, user_path(user) %><%= " (#{user.username})" %></td>
        <td><%= mail_to(user.email, user.email, encode: "javascript") %></td>
        <td><%= user.role.capitalize %></td>
				<% if current_user.role?(:admin) %>
					<td><a class="waves-effect waves-teal btn" <%= link_to "Edit", edit_user_path(user) %> </a></td>
				<% end %>
      </tr>
		<% end %>
	</tbody>
</table>

<%= will_paginate @inactive_users %>

app/views/users/_order_table.html.erb
<% unless @user_orders.empty? %>
  <table class="bordered highlight centered responsive-table">
    <thead>
      <tr>
        <td>Order ID</th>
        <th>Date</th>
        <th>School</th>
        <th>Amount</th>
        <th>Shipped On</th>
      </tr>
    </thead>
    <tbody>
      <% for order in @user_orders %>
        <tr>
          <td><%= link_to order.id, order_path(order) %>
          <td><%= order.date.strftime("%b %-d, %Y") %></td>
          <% if logged_in? && !(current_user.role?(:customer) || current_user.role?(:shipper)) %>
            <td><%= link_to order.school.name, school_path(order.school) %> </td>
          <% else %>
            <td><%= order.school.name %> </td>
          <% end %>
          <td><%= number_to_currency(order.grand_total) %> </td> 
          <% if order.order_items.to_a.max.shipped_on.nil? %>
            <td>---</td>
          <% else %>
            <td><%= order.order_items.to_a.max.shipped_on.strftime("%b %-d, %Y") %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  No associated orders exist in our system.
<% end %>

<!-- Add the pagination using will_paginate gem -->
<%= will_paginate @user_orders %>

app/views/users/edit.html.erb
<h4><i class="medium material-icons">edit</i>Edit User</h4>

<%= render partial: 'form' %>

app/views/users/index.html.erb
<p><h3>Viewing Users</h3>
<a class="waves-effect waves-light btn" <%= link_to "Add a New User", new_user_path %> </a>
</p>

<div class="row">
  <div class="col s12">
    <ul class="tabs tabs-fixed-width">
      <li class="tab col s3"><a href="#active">Active</a></li>
      <li class="tab col s3"><a href="#inactive">Inactive</a></li>
      <li class="tab col s3"><a href="#employees">Employees</a></li>
      <li class="tab col s3"><a href="#customers">Customers</a></li>
    </ul>
  </div>
  <div id="active" class="col s12">
    <% unless @active_users.empty? %>
      <%= render partial: "active_users" %>
    <% else %>
      <p>There are no active users in the system at this time.</p>
    <% end %>
  </div>
  <div id="inactive" class="col s12">
    <% unless @inactive_users.empty? %>
      <%= render partial: "inactive_users" %>
    <% else %>
      <p>There are no inactive users in the system at this time.</p>
    <% end %>
  </div>
  <div id="employees" class="col s12">
    <% unless @employees.empty? %>
      <%= render partial: "employees" %>
    <% else %>
      <p>There are no employees in the system at this time.</p>
    <% end %>
  </div>
  <div id="customers" class="col s12">
    <% unless @customers.empty? %>
      <%= render partial: "customers" %>
    <% else %>
      <p>There are no customers in the system at this time.</p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% if !logged_in? %>
  <h4><i class="medium material-icons">fiber_new</i>New Customer</h4>
  <h5>Please Note: We only ship schools, we will not ship to individuals.</h5>
<% elsif !current_user.role?(:manager) %>
  <h4><i class="medium material-icons">fiber_new</i>New User</h4>
<% else %>
  <h4><i class="medium material-icons">fiber_new</i>New Employee</h4>
<% end %>

<%= render partial: 'form' %>

app/views/users/show.html.erb
<h3><%= @user.proper_name %></h3>
<% if !@user.active %>
  <h5><b>INACTIVE</b></h5>
<% end %>
<p><b>Username: </b><%= @user.username %></p>
<p><b>Phone: </b><%= @reformatted_phone %></p>
<p><b>Email: </b><%= mail_to(@user.email, @user.email, encode: "javascript") %></p>
<em>A valued Chess Store <%= @user.role %> since <%= Date.current.year %>.</em>
<br><br>

<% if @user.role?(:customer) || @user.role?(:admin) %>
  <h5>Orders</h5>
  <%= render partial: 'order_table'%>
<% end %>

<!-- Managers can only edit other employees, not customers -->
<% unless current_user.role?(:manager) && @user.role?(:customer) %>
  <br>
  <a class="waves-effect waves-teal btn" <%= link_to "Edit Info", edit_user_path(@user) %> </a>
<% end %>