config/routes.rb
Rails.application.routes.draw do
  
  get 'errors/not_found'

  get 'errors/internal_server_error'

  # Routes for main resources
  resources :items
  resources :purchases
  resources :item_prices
  resources :users
  resources :schools
  resources :orders
  resources :sessions

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  # shipper ajax
  get "home/toggle/:id" => "home#toggle", as: :toggle

  # cart stuff
  get "view_cart" => "home#view_cart", as: :view_cart
  post "items/add_to_cart/:id" => "items#add_to_cart", as: :add_to_cart
  post "items/remove_one_from_cart/:id" => "items#remove_one_from_cart", as: :remove_one_from_cart
  post "items/delete_from_cart/:id" => "items#delete_from_cart", as: :delete_from_cart

  # error routes
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # Set the root url
  root :to => 'home#home'  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  include ChessStoreHelpers::Cart

  def home
    if logged_in? && (current_user.role?(:shipper) || current_user.role?(:admin))
      @not_shipped_orders = Order.not_shipped.chronological.paginate(:page => params[:page]).per_page(10)
    end
    @items_to_reorder = Item.need_reorder.alphabetical.to_a
  end

  def about
  end

  def contact
  end

  def privacy
  end

  def view_cart
    if !logged_in? || current_user.nil? || current_user.role?(:shipper) || current_user.role?(:manager)
      flash[:error] = "You are not authorized to take this action. Please log in as an appropriate user."
      redirect_to home_path
    end
    @cart_items = get_list_of_items_in_cart
  end

  def toggle
    @oi = OrderItem.find(params[:id])
    if @oi.shipped_on.nil?
      @oi.shipped
      flash[:notice] = "Marked #{@oi.quantity} #{@oi.item.name.pluralize(@oi.quantity)} as shipped."
    end
    @oi.save!
    @not_shipped_orders = Order.not_shipped.chronological
  end

end

app/views/home/_reorder_list.html.erb
<h4>Reorder List:</h4>
<% unless @items_to_reorder.empty? %>
  <table class="bordered highlight centered responsive-table">
    <thead>
      <tr>
        <th>Item</th>
        <th>Inventory</th>
        <th>Reorder Level</th>
        <% if current_user.role?(:admin) %>
          <th></th>
        <% end %>
        <th></th>
      </tr>
    </thead>
    
    <tbody>
      <% for item in @items_to_reorder %>
      <tr>
        <td><%= link_to item.name, item_path(item) %></td>
        <td><%= number_with_delimiter(item.inventory_level) %></td>
        <td><%= number_with_delimiter(item.reorder_level) %></td>
        <% if current_user.role?(:admin) %>
          <td><%= button_to "Add to Cart", add_to_cart_path(item) %></td>
        <% end %>
        <td><a class="waves-effect waves-teal btn" <%= link_to "Edit", edit_item_path(item) %> </a></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %> 
  No items need to be reordered at this time.
<% end %>

app/views/home/_shipper_list.html.erb
<div id="unshipped_orders">
  <% unless @not_shipped_orders.empty? %>
    <table class="bordered highlight centered responsive-table">
      <thead>
        <tr>
          <th>Order ID</th>
          <th>Item Name</th>
          <th>Quantity</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% for order in @not_shipped_orders %>
          <% for oi in order.order_items %>
            <tr>
              <% if oi.shipped_on.nil? %>
                <% if current_user.role?(:shipped) %>
                  <td><%= order.id %></td>
                   <td><%= oi.item.name %></td>
                <% else %>
                  <!-- the only other person seeing this will be an admin -->
                  <td><%= link_to order.id, order_path(order) %></td>
                  <td><%= link_to oi.item.name, item_path(oi.item) %></td>
                <% end %>
                <td><%= oi.quantity %></td>
                <td>
                  <%= link_to(toggle_path(oi), id: 'mark_shipped_button', class: 'button tiny radius', remote: true) do %>
                    Mark as Shipped
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% else %>
    All orders have been shipped! Good job!
  <% end %>
</div>

app/views/home/about.html.erb
<h3>About</h3>

<p>	<%= image_tag 'about.jpg', class: "left" %>
    Our store believes in the importance of scholastic chess.  To help support 
    scholastic chess, we make chess equipment available to schools and other educational 
    organizations at wholesale prices.  This chess equipment is only available to schools; 
    we do not sell to individuals.
</p>

app/views/home/contact.html.erb
<h3>Contact Us</h3>

<!-- Taken from PATs example, but modified a teeny tiny bit -->
<p>	<%= image_tag 'contact.jpg', class: "left" %>Unfortunately, Alex and Mark's
    Chess Store is not a real online website, but rather a project for 
    programming students at Carnegie Mellon University. We are sure that you 
    wanted to buy some chess items from the absolute best chess players on the 
    planet, but that's how it goes sometimes. We apologize for this, and if you 
    would like to contact someone about it, here is the contact info:</p>

<!-- Contact Info -->
<i class="material-icons prefix">call</i>
(908)-838-8767 <br>
<i class="material-icons prefix">location_city</i>
5000 Forbes Avenue Pittsburgh, PA 15213 <br>
<i class="material-icons prefix">email</i>
<%= mail_to("wpchu@andrew.cmu.edu", "Winston Chu: wpchu@andrew.cmu.edu", encode: "javascript") %> 

app/views/home/home.html.erb
<h3>Welcome to the Chess Store!</h3>

<% if !logged_in? || current_user.role?(:customer) %>
	<%= image_tag 'background.jpg', class: "left" %>
	<p> We are Alex and Mark Heimann, USCF and FIDE Chess
	Masters who have graduated from college and want to 
	help you! Our goal is help you develop your chess 
	skills and provide you with the necessary items to do so. 
	That's why we are committed to giving you the best products
	at the most affordable prices. If your school or 
	institution needs chess items, then this is the store
	for you! Happy shopping! </p>
	<% if !logged_in? %>
		<b>Note: Please <%= link_to "log in", login_path %> to our 
		   system or <%= link_to "create an account", new_user_path %> 
			 in order to add a school.</b> 
	<% elsif current_user.role?(:customer) %>
		<b><%= link_to "Click here to get started!", items_path %></b>
	<% end %>
<% elsif current_user.role?(:manager) %>
	<%= render partial: 'reorder_list' %>
<% elsif current_user.role?(:shipper) %>
	<h4>Unshipped Order Items:</h4>
	<%= render partial: 'shipper_list' %>
<% elsif current_user.role?(:admin) %>
	<%= render partial: 'reorder_list' %>
	<h4>Unshipped Order Items:</h4>
	<%= render partial: 'shipper_list' %>
<% end %>

app/views/home/privacy.html.erb
<h3>Privacy</h3>

<!-- Taken from PATs example, but modified a teeny tiny bit -->
<p> <%= image_tag 'privacy.jpg', class: "left" %>
	Our privacy policy is simple and does not require a lawyer 
	to understand it. We will pounce on the opportunity to sell every
	bit of information on you we have at our disposal in order 
	to boost our bottom line. We will gladly sell your 
	address, phone, email, age, chess statistics, name of
	favorite superhero, color of bunny slippers you wear at 
	home, and the like, to any willing buyer who will pay us the big bucks.  
	(BTW, we <em>know</em> you wear bunny slippers at home and   
	we know what color they are.  You really have no secrets 
	from us.)  If you have sensitive information that you don't want us to 
	share with the world, then keep it to yourself -- don't tell us.  
	<br><br>
	It's really that simple.
</p>

app/views/home/toggle.js.erb
$('#unshipped_orders').replaceWith('<%= j render("shipper_list") %>');

app/views/home/view_cart.html.erb
<h4>Your cart has <%= session[:cart].length %> <%= 'item'.pluralize(session[:cart].length) %>.</h4>

<% unless session[:cart].empty? %>
  <%= render partial: 'partials/cart_tables' %>

  <div id="checkout_button">
    <a class="waves-effect waves-light btn" <%= link_to "Proceed to Checkout", new_order_path %> </a>
  </div>
<% else %>
  <h5><em>Please place at least one item in your cart before checking out.</em></h5>
<% end %>