config/routes.rb
Rails.application.routes.draw do
  
  get 'errors/not_found'

  get 'errors/internal_server_error'

  # Routes for main resources
  resources :items
  resources :purchases
  resources :item_prices
  resources :users
  resources :schools
  resources :orders
  resources :sessions

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  # shipper ajax
  get "home/toggle/:id" => "home#toggle", as: :toggle

  # cart stuff
  get "view_cart" => "home#view_cart", as: :view_cart
  post "items/add_to_cart/:id" => "items#add_to_cart", as: :add_to_cart
  post "items/remove_one_from_cart/:id" => "items#remove_one_from_cart", as: :remove_one_from_cart
  post "items/delete_from_cart/:id" => "items#delete_from_cart", as: :delete_from_cart

  # error routes
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # Set the root url
  root :to => 'home#home'  

end

app/models/school.rb
class School < ActiveRecord::Base

  # get an array of the states in U.S.
  STATES_LIST = [['Alabama', 'AL'],['Alaska', 'AK'],['Arizona', 'AZ'],['Arkansas', 'AR'],['California', 'CA'],['Colorado', 'CO'],['Connectict', 'CT'],['Delaware', 'DE'],['District of Columbia ', 'DC'],['Florida', 'FL'],['Georgia', 'GA'],['Hawaii', 'HI'],['Idaho', 'ID'],['Illinois', 'IL'],['Indiana', 'IN'],['Iowa', 'IA'],['Kansas', 'KS'],['Kentucky', 'KY'],['Louisiana', 'LA'],['Maine', 'ME'],['Maryland', 'MD'],['Massachusetts', 'MA'],['Michigan', 'MI'],['Minnesota', 'MN'],['Mississippi', 'MS'],['Missouri', 'MO'],['Montana', 'MT'],['Nebraska', 'NE'],['Nevada', 'NV'],['New Hampshire', 'NH'],['New Jersey', 'NJ'],['New Mexico', 'NM'],['New York', 'NY'],['North Carolina','NC'],['North Dakota', 'ND'],['Ohio', 'OH'],['Oklahoma', 'OK'],['Oregon', 'OR'],['Pennsylvania', 'PA'],['Rhode Island', 'RI'],['South Carolina', 'SC'],['South Dakota', 'SD'],['Tennessee', 'TN'],['Texas', 'TX'],['Utah', 'UT'],['Vermont', 'VT'],['Virginia', 'VA'],['Washington', 'WA'],['West Virginia', 'WV'],['Wisconsin ', 'WI'],['Wyoming', 'WY']].freeze

  # Relationships
  has_many :orders
  has_many :users, through: :orders

  # Scopes
  scope :alphabetical,  -> { order(:name) }
  scope :active,        -> { where(active: true) }
  scope :inactive,      -> { where(active: false) }
  
  # Validations
  validates_presence_of :name, :street_1
  validates_format_of :zip, with: /\A\d{5}\z/, message: "should be five digits long"
  validates_inclusion_of :state, in: STATES_LIST.map{|key, value| value}, message: "is not an option"
  validates_numericality_of :min_grade, greater_than_or_equal_to: 0, less_than_or_equal_to: 12, only_integer: true, allow_blank: true
  validates_numericality_of :max_grade, greater_than_or_equal_to: :min_grade, less_than_or_equal_to: 12, only_integer: true, allow_blank: true
  validates_inclusion_of :state, in: STATES_LIST.to_h.values, message: "is not an option"
  validate :school_is_not_a_duplicate, on: :create

  def already_exists?
    School.where(name: self.name, zip: self.zip).size == 1
  end

  # Callbacks
  before_destroy :is_destroyable?
  after_rollback :make_inactive_if_trying_to_destroy

  # Other methods
  attr_reader :destroyable
  
  def is_destroyable?
    @destroyable = self.orders.empty?
  end
  
  private

  def make_inactive_if_trying_to_destroy
    if !@destroyable.nil? && @destroyable == false
      self.update_attribute(:active, false)
    end
    @destroyable = nil
  end

  def school_is_not_a_duplicate
    return true if self.name.nil? || self.street_1.nil? || self.zip.nil?
    if self.already_exists?
      errors.add(:name, "already exists for this school at this location")
    end
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  before_action :set_school, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @all_schools = School.all.alphabetical.paginate(:page => params[:page]).per_page(10)
  end

  def edit
  end

  def new
    @school = School.new
  end

  def show
    @school_orders = @school.orders.chronological.paginate(:page => params[:page]).per_page(10)
  end

  def create
    @school = School.new(school_params)
    if @school.save
      if can? :read, @school
        redirect_to school_path(@school), notice: "Successfully added #{@school.name} to our system."
      else
          redirect_to home_path, notice: "Successfully added #{@school.name} to our system."
      end
    else
      render action: 'new'
    end
  end

  def update
    if @school.update(school_params)
      redirect_to school_path(@school), notice: "Successfully updated #{@school.name}."
    else
      render action: 'edit'
    end
  end

  def destroy
    if !@school.is_destroyable?
      flash[:error] = "Could not remove #{@school.name}. Set as inactive."
      @school.active = false
      @school.save!
      redirect_to :back
    else
      @school.destroy
      redirect_to schools_path, notice: "Successfully removed #{@school.name} from the system."
    end
  end

  private

  def set_school
    @school = School.find(params[:id])
  end

  def school_params
    params.require(:school).permit(:name, :street_1, :street_2, :city, :state, :zip, :min_grade, :max_grade, :active) 
  end

end

app/views/schools/_form.html.erb
<div class="row">
	<%= simple_form_for(@school) do |f| %>

		<!-- Display errors, if any -->
		<% if @school.errors.any? %>
			<div id="error_explanation">
				<h6><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h6>
				<% @school.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</div>
  	<% end %>
		
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">business</i>
				<%= f.label :name %>
    		<%= f.text_field :name %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">place</i>
				<%= f.label :street_1 %>
    		<%= f.text_field :street_1 %>
			</div>
    </div>
    <div class="row">
      <div class="input-field col s10">
        <i class="material-icons prefix">place</i>
        <%= f.label :street_2 %>
        <%= f.text_field :street_2 %>
      </div>
      </div>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">location_city</i>
				<%= f.label :city %>
    		<%= f.text_field :city %>
			</div>
			<div class="input-field col s10">
				<i class="material-icons prefix">terrain</i>
				<%= f.label :state %><br><br>
    		<%= f.select :state, School::STATES_LIST, { :include_blank => 'Select a state...' } %>
			</div>
			<div class="input-field col s10">
				<i class="material-icons prefix">art_track</i>
				<%= f.label :zip %>
    		<%= f.number_field :zip %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">arrow_downward</i>
				<%= f.label :min_grade %>
    		<%= f.number_field :min_grade %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s10">
				<i class="material-icons prefix">arrow_upward</i>
				<%= f.label :max_grade %>
    		<%= f.number_field :max_grade %>
			</div>
		</div>
		<% if logged_in? && current_user.role?(:admin) %>
			<div class="row">
				<div class="input-field col s10">
					<%= f.input :active, as: :boolean %>
				</div>
			</div>
		<% end %>
		<div class ="row">
			<div class="input-field col s10">
				<button class="btn waves-effect waves-light">
					<i class="material-icons right">school</i>
					<%= f.submit %>
				</button>
			</div>
		</div>
	<% end %>
</div>

app/views/schools/_school_order_table.html.erb
<% unless @school_orders.empty? %>
  <table class="bordered highlight centered responsive-table">
    <thead>
      <tr>
        <th>Order ID</th>
        <th>Date</th>
        <th>User</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      <% for order in @school_orders %>
        <tr>
          <td><%= link_to order.id, order_path(order) %>
          <td><%= order.date.strftime("%b %-d, %Y") %></td>
          <% if logged_in? && !(current_user.role?(:customer) || current_user.role?(:shipper)) %>
            <td><%= link_to order.user.proper_name, user_path(order.user) %> </td>
          <% else %>
            <td><%= order.user.proper_name %> </td>
          <% end %>
          <td><%= number_to_currency(order.grand_total) %> </td> 
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  No associated orders exist in our system.
<% end %>

app/views/schools/edit.html.erb
<h4><i class="medium material-icons">edit</i>Edit School</h4>

<%= render partial: 'form' %>

app/views/schools/index.html.erb
<p><h3>Viewing Schools</h3>
<a class="waves-effect waves-light btn" <%= link_to "Add a New School", new_school_path %> </a>
</p>

<!-- Display a table showing information of all the boards -->
<table class="bordered highlight centered responsive-table">
	<thead>
		<tr>
			<th>Name</th>
      <th>City, State</th>
      <th>Active</th>
		</tr>
	</thead>

	<tbody>
		<% for school in @all_schools %>
      <tr>
        <td><%= link_to school.name, school_path(school) %></td>
        <td><%= school.city %>, <%= school.state %></td>
        <td>
          <% if school.active? %>
            Y
          <% else %>
            N
          <% end %>
        </td>
      </tr>
		<% end %>
	</tbody>
</table>

<%= will_paginate @all_schools %>

app/views/schools/new.html.erb
<h4><i class="medium material-icons">fiber_new</i>Add a School to our System</h4>

<%= render partial: 'form' %>

app/views/schools/show.html.erb
<h3><%= @school.name %></h3>
<% if !@school.active %>
  <h5><b>INACTIVE</b></h5>
<% end %>
<p><b>Address:</b><br>
<%= @school.street_1 %><br>
<% unless @school.street_2.nil? %>
  <%= @school.street_2 %><br>
<% end %>
<%= @school.city %>, <%= @school.state %> <%= @school.zip %><br>
United States</p>

<p><b>Mininum Grade: </b>
<% unless @school.min_grade.nil?%>
  <%= @school.min_grade %>
<% else %>
  N/A
<% end %><p>

<p><b>Maximum Grade: </b>
<% unless @school.max_grade.nil?%>
  <%= @school.max_grade %>
<% else %>
  N/A
<% end %><p>

<b>School Orders: </b>
<%= render partial: 'school_order_table' %>

<br>
<br>
<% if current_user.role?(:admin) %>
  <a class="waves-effect waves-teal btn" <%= link_to "Edit School", edit_school_path(@school) %> </a>
  <a class="waves-effect waves-red btn tooltipped" data-position="top" data-delay="10" data-tooltip="Are you sure?" <%= link_to "Delete", @item, method: :delete %> </a>
<% end %>